name: Metrics
on:
  schedule: [{cron: "0 0 */1 * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.PRO_TOKEN }}

          # Options
          user: zhaozuodong
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
